language: cpp
compiler: gcc
node_js: "5"

install:
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-none-eabi
  - npm install
  - gulp setup

script: gulp build:firmware && gulp test
