language: cpp
compiler: gcc
dist: trusty
node_js: "5"

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded
  - sudo apt-get install -y cmake cmake-data
  - cmake --version
  - node --version

install:
  - npm install
  - gulp setup

script: gulp build:firmware && gulp test
