language: cpp
compiler: clang
dist: trusty
node_js: "5"

before_install:
  - sudo add-apt-repository ppa:team-gcc-arm-embedded/ppa -y
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-arm-embedded

# From https://github.com/boostorg/hana/blob/master/.travis.yml
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR}
  - cd ${DEPS_DIR}
  - CMAKE_URL="https://cmake.org/files/v3.6/cmake-3.6.0-Linux-x86_64.tar.gz"
  - mkdir cmake
  - travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
  - export PATH=${DEPS_DIR}/cmake/bin:${PATH}
  - cd ${TRAVIS_BUILD_DIR}

  - cmake --version
  - node --version

install:
  - npm install
  - gulp setup

script: gulp build:firmware && VERBOSE=1 gulp test
